name: tasks_app
description: "Aplicativo de lista de tarefas"

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: 7.2.0
  flutter_screenutil: 5.9.0
  get: 4.6.5
  auto_injector: 2.0.4
  shared_preferences: 2.0.15
  mockito: ^5.4.4

  #--- FIREBASE --- 
  # firebase_core: 2.17.0
  # firebase_auth: 4.10.1
  # firebase_database: 10.2.7
  # firebase_core_web: 2.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito:
  build_runner:

flutter:
  uses-material-design: true

  fonts:
    - family: Figtree
      fonts:
        # - asset: assets/fonts/Figree
        #   weight: 100
        - asset: assets/fonts/Figtree/static/Figtree-Light.ttf
          weight: 300
        - asset: assets/fonts/Figtree/static/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree/static/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree/static/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree/static/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree/static/Figtree-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Figtree/static/Figtree-Black.ttf
          weight: 900